version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    restart: unless-stopped
    networks:
      - backend-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend-net

  fastapi:
    build:
      context: .
      dockerfile: DockerfileFastapi
    image: fastapi-image
    container_name: fastapi
    ports:
      - "8000"
    environment:
      RMQ_URL: ${RMQ_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped
    networks:
      - backend-net

  celery:
    build:
      context: .
      dockerfile: DockerfileCelery
    image: celery-image
    container_name: celery
    environment:
      RMQ_URL: ${RMQ_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge